package pojo;
// Generated Oct 22, 2020 4:56:21 PM by Hibernate Tools 4.3.1

import DAO.DAObarang;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;

/**
 * Barang generated by hbm2java
 */
@ManagedBean
public class Barang implements java.io.Serializable {

    private Integer idBarang;
    private String name;
    private String category;
    private int quantity;
    private int price;
    private String picture;
    private String detail;

    public List<Barang> getAllRecord() {
        DAObarang prd = new DAObarang();
        List<Barang> Lprd = prd.retrieveBarang();
        return Lprd;
    }

    public void save_prd() {
        DAObarang add = new DAObarang();
        add.add_prd(this);
    }

    public String getById() {
        String id_prd = idBarang.toString();
        DAObarang prd = new DAObarang();
        List<Barang> lprd = prd.getbyID(id_prd);
        name = lprd.get(0).name;
        category = lprd.get(0).category;
        quantity = lprd.get(0).quantity;
        price = lprd.get(0).price;
        picture = lprd.get(0).picture;
        detail = lprd.get(0).detail;
        return "admin";
    }

    public String edit() {
        DAObarang usr = new DAObarang();
        usr.editPrd(this);
        name = "";
        category = "";
        quantity = 0;
        price = 0;
        picture = "";
        detail = "";
        FacesMessage facesMessage = new FacesMessage(FacesMessage.SEVERITY_INFO, "Berhasill Update Data", null);
        return "admin";
    }

    public String delete() {
        DAObarang usr = new DAObarang();
        usr.deletePrd(idBarang);
        name = "";
        category = "";
        quantity = 0;
        price = 0;
        picture = "";
        detail = "";
        return "admin";
    }

    public Barang() {
    }

    public Barang(String name, String category, int quantity, int price, String picture, String detail) {
        this.name = name;
        this.category = category;
        this.quantity = quantity;
        this.price = price;
        this.picture = picture;
        this.detail = detail;
    }

    public Integer getIdBarang() {
        return this.idBarang;
    }

    public void setIdBarang(Integer idBarang) {
        this.idBarang = idBarang;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCategory() {
        return this.category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getPrice() {
        return this.price;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public String getPicture() {
        return this.picture;
    }

    public void setPicture(String picture) {
        this.picture = picture;
    }

    public String getDetail() {
        return this.detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

}
