package pojo;
// Generated Oct 26, 2020 12:40:27 PM by Hibernate Tools 4.3.1

import DAO.DAObarang;
import DAO.DAOcart;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpSession;




/**
 * Ordertbl generated by hbm2java
 */
@ManagedBean
public class Ordertbl  implements java.io.Serializable {


     private Integer orderId;
     private String email;
     private String product;
     private int quantity;
     private int price;
     
     public List<Ordertbl> getAllRecord() {
        DAOcart order = new DAOcart();
        List<Ordertbl> Lord = order.retrieveOrder();
        return Lord;
    }
     
     public void save_prd(Barang barang) {
        product = barang.getName();
        price = barang.getPrice();
        quantity = 1;
        FacesContext facesContext = FacesContext.getCurrentInstance();
        HttpSession session = (HttpSession) facesContext.getExternalContext().getSession(false);
        email = session.getAttribute("user_session_email").toString();
        DAOcart add = new DAOcart();
        add.add_order(this);
        System.out.println(quantity);
    }

    public Ordertbl() {
    }

    public Ordertbl(String email, String product, int quantity, int price) {
       this.email = email;
       this.product = product;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getProduct() {
        return this.product;
    }
    
    public void setProduct(String product) {
        this.product = product;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }




}


